FileVersion = 1
Dependencies = {GlitchyEngine = "*", corlib = "*", LodePng = "*", msdfgen-beef = "*"}

[Project]
Name = "Sandbox"
TargetType = "BeefGUIApplication"
StartupObject = "GlitchyEngine.Program"
ProcessorMacros = ["SANDBOX_2D"]

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
