FileVersion = 1
Dependencies = {GlitchyEngine = "*", corlib = "*", msdfgen-beef = "*", LodePng = "*"}

[Project]
Name = "Sandbox"
TargetType = "BeefGUIApplication"
StartupObject = "GlitchyEngine.Program"
ProcessorMacros = ["GAMMA_TEST", "NOT_SANDBOX_2D"]
