FileVersion = 1
Dependencies = {GlitchyEngine = "*", corlib = "*"}

[Project]
Name = "Sandbox"
TargetType = "BeefGUIApplication"
StartupObject = "GlitchyEngine.Program"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
