FileVersion = 1

[Project]
Name = "GlitchyEngine.Benchmark"
StartupObject = "GlitchyEngine.Benchmark.BenchmarkApp"

[Dependencies]
corlib = "*"
GlitchyEngine = "*"

[Configs.Debug.Win64]
DebugWorkingDirectory = "d:\\Development\\Projects\\Beef\\GlitchyEngine\\GlitchyEditor"

[Configs.Release.Win64]
DebugWorkingDirectory = "d:\\Development\\Projects\\Beef\\GlitchyEngine\\GlitchyEditor"
