FileVersion = 1

[Project]
Name = "EditorUI"
TargetType = "BeefLib"
StartupObject = "EditorUI.Program"

[Configs.Debug.Win64]
BuildKind = "StaticLib"
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
PreBuildCmds = ["npm run build"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist\")"]
