FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", DirectX = "*"}

[Project]
Name = "GlitchyEngineHelper"
TargetType = "BeefLib"
StartupObject = "GlitchyEngineHelper.Program"

[Configs.Debug.Win64]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
LibPaths = ["$(ProjectDir)/out/build/x64-debug/GlitchyEngineHelper.lib", "ws2_32.lib", "Winmm.lib", "OleAut32.lib", "Bcrypt.lib"]

[Configs.Release.Win64]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
LibPaths = ["$(ProjectDir)/out/build/x64-debug/GlitchyEngineHelper.lib", "ws2_32.lib", "Winmm.lib", "OleAut32.lib", "Bcrypt.lib"]
