FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", DirectX = "*"}

[Project]
Name = "GlitchyEngineHelper"
TargetType = "BeefLib"
StartupObject = "GlitchyEngineHelper.Program"

[Configs.Debug.Win64]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
LibPaths = ["$(ProjectDir)/out/build/x64-debug/GlitchyEngineHelper.lib"]
PreBuildCmds = ["$(ProjectDir)/../bin/vscmake.bat x64 $(ProjectDir) x64-debug"]

[Configs.Release.Win64]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
LibPaths = ["$(ProjectDir)/out/build/x64-release/GlitchyEngineHelper.lib"]
PreBuildCmds = ["$(ProjectDir)/../bin/vscmake.bat x64 $(ProjectDir) x64-release"]
