FileVersion = 1
Dependencies = {corlib = "*", GlitchyEngine = "*", corlib = "*"}

[Project]
Name = "GlitchyEngine.Test"
StartupObject = "GlitchyEngine.Test.TestApp"

[Configs.Debug.Win64]
DebugWorkingDirectory = "D:\\Development\\Projects\\Beef\\GlitchyEngine\\GlitchyEditor"

[Configs.Test.Win64]
DebugWorkingDirectory = "$(WorkspaceDir)\\GlitchyEditor"
