FileVersion = 1
Dependencies = {GlitchLog = "*", corlib = "*", DirectX = "*", ImGui = "*", ImGuiImplWin32 = "*", ImGuiImplDX11 = "*"}

[Project]
Name = "GlitchyEngine"
ProcessorMacros = ["GE_ERROR_SHADER_MATRIX_MISMATCH", "GE_ERROR_SHADER_VAR_TYPE_MISMATCH"]

[Configs.Debug.Win32]
PreprocessorMacros = ["DEBUG", "GE_WINDOWS"]

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
PreprocessorMacros = ["DEBUG", "GE_WINDOWS"]

[Configs.Release.Win32]
PreprocessorMacros = ["RELEASE", "GE_WINDOWS"]

[Configs.Release.Win64]
PreprocessorMacros = ["RELEASE", "GE_WINDOWS"]

[Configs.Paranoid.Win32]
PreprocessorMacros = ["DEBUG", "PARANOID", "GE_WINDOWS"]

[Configs.Paranoid.Win64]
PreprocessorMacros = ["DEBUG", "PARANOID", "GE_WINDOWS"]

[Configs.Test.Win32]
PreprocessorMacros = ["TEST", "GE_WINDOWS"]

[Configs.Test.Win64]
PreprocessorMacros = ["TEST", "GE_WINDOWS"]
