FileVersion = 1

[Project]
Name = "ScriptCore"
TargetType = "CustomBuild"

[Configs.Debug.Win64]
PostBuildCmds = ["$(WorkspaceDir)/bin/BuildTool.exe build ScriptCore -n --workspace $(WorkspaceDir) --debug"]

[Configs.Release.Win64]
PostBuildCmds = ["$(WorkspaceDir)/bin/BuildTool.exe build ScriptCore -n --workspace $(WorkspaceDir) --release"]
